neTCLib: Foam::species::thermo2T< Thermo2T, Type > Class Template Reference
Foam::species::thermo2T< Thermo2T, Type > Class Template Reference
#include <thermo2T.H>
Public Types
typedef thermo2T< Thermo2T, Type > thermoType
typedef thermo2T< Thermo2T, Type > thermoType
Public Member Functions
thermo2T (const Thermo2T &sp)
thermo2T (const dictionary &dict)
thermo2T (const word &name, const thermo2T &)
scalar CpvTR (const scalar p, const scalar TTR) const
scalar gamma (const scalar p, const scalar TTR) const
scalar CpByCpvTR (const scalar p, const scalar TTR) const
scalar HE (const scalar p, const scalar TTR) const
scalar G (const scalar p, const scalar TTR) const
scalar A (const scalar p, const scalar TTR) const
scalar cpTR (const scalar p, const scalar TTR) const
scalar ha (const scalar p, const scalar TTR) const
scalar hs (const scalar p, const scalar TTR) const
scalar hc () const
scalar s (const scalar p, const scalar TTR) const
scalar he (const scalar p, const scalar TTR) const
scalar cvT (const scalar p, const scalar TTR) const
scalar cvR (const scalar p, const scalar TTR) const
scalar cvVib (const scalar p, const scalar TTR, const scalar TVib, const scalar ThetaVib) const
scalar esT (const scalar p, const scalar TTR) const
scalar eaT (const scalar p, const scalar TTR) const
scalar esR (const scalar p, const scalar TTR) const
scalar esVib (const scalar p, const scalar TTR, const scalar TVib, const scalar ThetaVib) const
scalar g (const scalar p, const scalar TTR) const
scalar a (const scalar p, const scalar TTR) const
scalar K (const scalar p, const scalar TTR) const
scalar Kp (const scalar p, const scalar TTR) const
scalar Kc (const scalar p, const scalar TTR) const
scalar Kx (const scalar p, const scalar TTR) const
scalar Kn (const scalar p, const scalar TTR, const scalar n) const
scalar THE_TR (const scalar H, const scalar p, const scalar TTR0) const
scalar TEH_Vib (const scalar esVib, const scalar p, const scalar TTR0, const scalar TVib0) const
scalar THs_TR (const scalar Hs, const scalar p, const scalar TTR0) const
scalar THa_TR (const scalar H, const scalar p, const scalar TTR0) const
scalar TEs_TR (const scalar E, const scalar p, const scalar TTR0) const
scalar TEs_Vib (const scalar E, const scalar p, const scalar TTR0, const scalar TVib0) const
scalar TEa_TR (const scalar E, const scalar p, const scalar TTR0) const
scalar dKcdTbyKc (const scalar p, const scalar TTR) const
scalar dcpdT (const scalar p, const scalar TTR) const
void write (Ostream &os) const
void operator+= (const thermo2T &)
void operator*= (const scalar)
thermo2T (const Thermo2T &sp)
thermo2T (const dictionary &dict)
thermo2T (const word &name, const thermo2T &)
scalar CpvTR (const scalar p, const scalar TTR) const
scalar gamma (const scalar p, const scalar TTR) const
scalar CpByCpvTR (const scalar p, const scalar TTR) const
scalar HE (const scalar p, const scalar TTR) const
scalar G (const scalar p, const scalar TTR) const
scalar A (const scalar p, const scalar TTR) const
scalar cpTR (const scalar p, const scalar TTR) const
scalar ha (const scalar p, const scalar TTR) const
scalar hs (const scalar p, const scalar TTR) const
scalar hc () const
scalar s (const scalar p, const scalar TTR) const
scalar he (const scalar p, const scalar TTR) const
scalar cvT (const scalar p, const scalar TTR) const
scalar cvR (const scalar p, const scalar TTR) const
scalar cvVib (const scalar p, const scalar TTR, const scalar TVib, const scalar ThetaVib) const
scalar esT (const scalar p, const scalar TTR) const
scalar eaT (const scalar p, const scalar TTR) const
scalar esR (const scalar p, const scalar TTR) const
scalar esVib (const scalar p, const scalar TTR, const scalar TVib, const scalar ThetaVib) const
scalar g (const scalar p, const scalar TTR) const
scalar a (const scalar p, const scalar TTR) const
scalar K (const scalar p, const scalar TTR) const
scalar Kp (const scalar p, const scalar TTR) const
scalar Kc (const scalar p, const scalar TTR) const
scalar Kx (const scalar p, const scalar TTR) const
scalar Kn (const scalar p, const scalar TTR, const scalar n) const
scalar THE_TR (const scalar H, const scalar p, const scalar TTR0) const
scalar TEH_Vib (const scalar esVib, const scalar p, const scalar TTR0, const scalar TVib0) const
scalar THs_TR (const scalar Hs, const scalar p, const scalar TTR0) const
scalar THa_TR (const scalar H, const scalar p, const scalar TTR0) const
scalar TEs_TR (const scalar E, const scalar p, const scalar TTR0) const
scalar TEs_Vib (const scalar E, const scalar p, const scalar TTR0, const scalar TVib0) const
scalar TEa_TR (const scalar E, const scalar p, const scalar TTR0) const
scalar dKcdTbyKc (const scalar p, const scalar TTR) const
scalar dcpdT (const scalar p, const scalar TTR) const
void write (Ostream &os) const
void operator+= (const thermo2T &)
void operator*= (const scalar)
Static Public Member Functions
static word typeName ()
static word heName ()
static word typeName ()
static word heName ()
Friends
thermo2T operator+ (const thermo2T &, const thermo2T &)
thermo2T operator* (const scalar s, const thermo2T &)
thermo2T operator== (const thermo2T &, const thermo2T &)
Ostream & operator (Ostream &, const thermo2T &)
thermo2T operator+ (const thermo2T &, const thermo2T &)
thermo2T operator* (const scalar s, const thermo2T &)
thermo2T operator== (const thermo2T &, const thermo2T &)
Ostream & operator (Ostream &, const thermo2T &)
Detailed Description
template<class Thermo2T, template< class > class Type>
class Foam::species::thermo2T< Thermo2T, Type >
Definition at line 92 of file thermo/thermo2T/thermo2T.H.
Member Typedef Documentation
thermoType [1/2]
template<class Thermo2T , template< class > class Type> typedef thermo2T<Thermo2T, Type> Foam::species::thermo2T< Thermo2T, Type >::thermoType
Definition at line 136 of file lnInclude/thermo2T.H.
thermoType [2/2]
template<class Thermo2T , template< class > class Type> typedef thermo2T<Thermo2T, Type> Foam::species::thermo2T< Thermo2T, Type >::thermoType
Definition at line 136 of file thermo/thermo2T/thermo2T.H.
Constructor & Destructor Documentation
thermo2T() [1/6]
template<class Thermo2T , template< class > class Type> Foam::species::thermo2T< Thermo2T, Type >::thermo2T (const Thermo2T & sp) inline
Definition at line 34 of file lnInclude/thermo2TI.H.
thermo2T() [2/6]
template<class Thermo2T , template< class > class Type> Foam::species::thermo2T< Thermo2T, Type >::thermo2T (const dictionary & dict)
Definition at line 42 of file lnInclude/thermo2T.C.
thermo2T() [3/6]
template<class Thermo2T , template< class > class Type> Foam::species::thermo2T< Thermo2T, Type >::thermo2T (const word & name, const thermo2T< Thermo2T, Type > & st) inline
Definition at line 144 of file lnInclude/thermo2TI.H.
thermo2T() [4/6]
template<class Thermo2T , template< class > class Type> Foam::species::thermo2T< Thermo2T, Type >::thermo2T (const Thermo2T & sp) inline
thermo2T() [5/6]
template<class Thermo2T , template< class > class Type> Foam::species::thermo2T< Thermo2T, Type >::thermo2T (const dictionary & dict)
thermo2T() [6/6]
template<class Thermo2T , template< class > class Type> Foam::species::thermo2T< Thermo2T, Type >::thermo2T (const word & name, const thermo2T< Thermo2T, Type > &) inline
Member Function Documentation
A() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::A (const scalar p, const scalar TTR) const inline
Definition at line 216 of file lnInclude/thermo2TI.H.
a() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::a (const scalar p, const scalar TTR) const inline
Definition at line 330 of file lnInclude/thermo2TI.H.
A() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::A (const scalar p, const scalar TTR) const inline
a() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::a (const scalar p, const scalar TTR) const inline
CpByCpvTR() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::CpByCpvTR (const scalar p, const scalar TTR) const inline
Definition at line 188 of file lnInclude/thermo2TI.H.
CpByCpvTR() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::CpByCpvTR (const scalar p, const scalar TTR) const inline
cpTR() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::cpTR (const scalar p, const scalar TTR) const inline
Definition at line 224 of file lnInclude/thermo2TI.H.
References CpTR().
cpTR() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::cpTR (const scalar p, const scalar TTR) const inline
CpvTR() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::CpvTR (const scalar p, const scalar TTR) const inline
Definition at line 166 of file lnInclude/thermo2TI.H.
CpvTR() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::CpvTR (const scalar p, const scalar TTR) const inline
cvR() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::cvR (const scalar p, const scalar TTR) const inline
Definition at line 279 of file lnInclude/thermo2TI.H.
References CvR().
cvR() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::cvR (const scalar p, const scalar TTR) const inline
cvT() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::cvT (const scalar p, const scalar TTR) const inline
Definition at line 272 of file lnInclude/thermo2TI.H.
References CvT().
cvT() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::cvT (const scalar p, const scalar TTR) const inline
cvVib() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::cvVib (const scalar p, const scalar TTR, const scalar TVib, const scalar ThetaVib) const inline
Definition at line 286 of file lnInclude/thermo2TI.H.
References CvVib().
cvVib() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::cvVib (const scalar p, const scalar TTR, const scalar TVib, const scalar ThetaVib) const inline
dcpdT() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::dcpdT (const scalar p, const scalar TTR) const inline
Definition at line 569 of file lnInclude/thermo2TI.H.
dcpdT() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::dcpdT (const scalar p, const scalar TTR) const inline
dKcdTbyKc() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::dKcdTbyKc (const scalar p, const scalar TTR) const inline
Definition at line 546 of file lnInclude/thermo2TI.H.
dKcdTbyKc() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::dKcdTbyKc (const scalar p, const scalar TTR) const inline
eaT() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::eaT (const scalar p, const scalar TTR) const inline
Definition at line 314 of file lnInclude/thermo2TI.H.
References EaT().
eaT() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::eaT (const scalar p, const scalar TTR) const inline
esR() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::esR (const scalar p, const scalar TTR) const inline
Definition at line 300 of file lnInclude/thermo2TI.H.
References EsR().
esR() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::esR (const scalar p, const scalar TTR) const inline
esT() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::esT (const scalar p, const scalar TTR) const inline
Definition at line 293 of file lnInclude/thermo2TI.H.
References EsT().
esT() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::esT (const scalar p, const scalar TTR) const inline
esVib() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::esVib (const scalar p, const scalar TTR, const scalar TVib, const scalar ThetaVib) const inline
Definition at line 307 of file lnInclude/thermo2TI.H.
References EsVib().
esVib() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::esVib (const scalar p, const scalar TTR, const scalar TVib, const scalar ThetaVib) const inline
G() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::G (const scalar p, const scalar TTR) const inline
Definition at line 208 of file lnInclude/thermo2TI.H.
g() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::g (const scalar p, const scalar TTR) const inline
Definition at line 322 of file lnInclude/thermo2TI.H.
G() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::G (const scalar p, const scalar TTR) const inline
g() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::g (const scalar p, const scalar TTR) const inline
gamma() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::gamma (const scalar p, const scalar TTR) const inline
Definition at line 174 of file lnInclude/thermo2TI.H.
References CpTR().
gamma() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::gamma (const scalar p, const scalar TTR) const inline
ha() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::ha (const scalar p, const scalar TTR) const inline
Definition at line 232 of file lnInclude/thermo2TI.H.
ha() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::ha (const scalar p, const scalar TTR) const inline
hc() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::hc () const inline
Definition at line 248 of file lnInclude/thermo2TI.H.
hc() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::hc () const inline
HE() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::HE (const scalar p, const scalar TTR) const inline
Definition at line 200 of file lnInclude/thermo2TI.H.
he() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::he (const scalar p, const scalar TTR) const inline
Definition at line 264 of file lnInclude/thermo2TI.H.
HE() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::HE (const scalar p, const scalar TTR) const inline
he() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::he (const scalar p, const scalar TTR) const inline
heName() [1/2]
template<class Thermo2T , template< class > class Type> Foam::word Foam::species::thermo2T< Thermo2T, Type >::heName () inline static
Definition at line 158 of file lnInclude/thermo2TI.H.
heName() [2/2]
template<class Thermo2T , template< class > class Type> static word Foam::species::thermo2T< Thermo2T, Type >::heName () inline static
hs() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::hs (const scalar p, const scalar TTR) const inline
Definition at line 240 of file lnInclude/thermo2TI.H.
hs() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::hs (const scalar p, const scalar TTR) const inline
K() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::K (const scalar p, const scalar TTR) const inline
Definition at line 338 of file lnInclude/thermo2TI.H.
K() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::K (const scalar p, const scalar TTR) const inline
Kc() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::Kc (const scalar p, const scalar TTR) const inline
Definition at line 363 of file lnInclude/thermo2TI.H.
Kc() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::Kc (const scalar p, const scalar TTR) const inline
Kn() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::Kn (const scalar p, const scalar TTR, const scalar n) const inline
Definition at line 399 of file lnInclude/thermo2TI.H.
Kn() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::Kn (const scalar p, const scalar TTR, const scalar n) const inline
Kp() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::Kp (const scalar p, const scalar TTR) const inline
Definition at line 355 of file lnInclude/thermo2TI.H.
Kp() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::Kp (const scalar p, const scalar TTR) const inline
Kx() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::Kx (const scalar p, const scalar TTR) const inline
Definition at line 379 of file lnInclude/thermo2TI.H.
Kx() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::Kx (const scalar p, const scalar TTR) const inline
operator*=() [1/2]
template<class Thermo2T , template< class > class Type> void Foam::species::thermo2T< Thermo2T, Type >::operator*= (const scalar s) inline
Definition at line 587 of file lnInclude/thermo2TI.H.
operator*=() [2/2]
template<class Thermo2T , template< class > class Type> void Foam::species::thermo2T< Thermo2T, Type >::operator*= (const scalar) inline
operator+=() [1/2]
template<class Thermo2T , template< class > class Type> void Foam::species::thermo2T< Thermo2T, Type >::operator+= (const thermo2T< Thermo2T, Type > & st) inline
Definition at line 577 of file lnInclude/thermo2TI.H.
operator+=() [2/2]
template<class Thermo2T , template< class > class Type> void Foam::species::thermo2T< Thermo2T, Type >::operator+= (const thermo2T< Thermo2T, Type > &) inline
s() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::s (const scalar p, const scalar TTR) const inline
Definition at line 256 of file lnInclude/thermo2TI.H.
s() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::s (const scalar p, const scalar TTR) const inline
TEa_TR() [1/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::TEa_TR (const scalar E, const scalar p, const scalar TTR0) const inline
TEa_TR() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::TEa_TR (const scalar E, const scalar p, const scalar TTR0) const inline
TEH_Vib() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::TEH_Vib (const scalar esVib, const scalar p, const scalar TTR0, const scalar TVib0) const inline
Definition at line 431 of file lnInclude/thermo2TI.H.
TEH_Vib() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::TEH_Vib (const scalar esVib, const scalar p, const scalar TTR0, const scalar TVib0) const inline
TEs_TR() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::TEs_TR (const scalar E, const scalar p, const scalar TTR0) const inline
Definition at line 484 of file lnInclude/thermo2TI.H.
TEs_TR() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::TEs_TR (const scalar E, const scalar p, const scalar TTR0) const inline
TEs_Vib() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::TEs_Vib (const scalar E, const scalar p, const scalar TTR0, const scalar TVib0) const inline
Definition at line 503 of file lnInclude/thermo2TI.H.
TEs_Vib() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::TEs_Vib (const scalar E, const scalar p, const scalar TTR0, const scalar TVib0) const inline
THa_TR() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::THa_TR (const scalar H, const scalar p, const scalar TTR0) const inline
Definition at line 464 of file lnInclude/thermo2TI.H.
THa_TR() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::THa_TR (const scalar H, const scalar p, const scalar TTR0) const inline
THE_TR() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::THE_TR (const scalar H, const scalar p, const scalar TTR0) const inline
Definition at line 420 of file lnInclude/thermo2TI.H.
THE_TR() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::THE_TR (const scalar H, const scalar p, const scalar TTR0) const inline
THs_TR() [1/2]
template<class Thermo2T , template< class > class Type> Foam::scalar Foam::species::thermo2T< Thermo2T, Type >::THs_TR (const scalar Hs, const scalar p, const scalar TTR0) const inline
Definition at line 444 of file lnInclude/thermo2TI.H.
THs_TR() [2/2]
template<class Thermo2T , template< class > class Type> scalar Foam::species::thermo2T< Thermo2T, Type >::THs_TR (const scalar Hs, const scalar p, const scalar TTR0) const inline
typeName() [1/2]
template<class Thermo2T , template< class > class Type> static word Foam::species::thermo2T< Thermo2T, Type >::typeName () inline static
Definition at line 154 of file lnInclude/thermo2T.H.
References Foam::species::thermo2T< Thermo2T, Type >::typeName().
Referenced by Foam::species::thermo2T< Thermo2T, Type >::typeName().
typeName() [2/2]
template<class Thermo2T , template< class > class Type> static word Foam::species::thermo2T< Thermo2T, Type >::typeName () inline static
Definition at line 154 of file thermo/thermo2T/thermo2T.H.
References Foam::species::thermo2T< Thermo2T, Type >::typeName().
write() [1/2]
template<class Thermo2T , template< class > class Type> void Foam::species::thermo2T< Thermo2T, Type >::write (Ostream & os) const
Definition at line 51 of file lnInclude/thermo2T.C.
write() [2/2]
template<class Thermo2T , template< class > class Type> void Foam::species::thermo2T< Thermo2T, Type >::write (Ostream & os) const
Friends And Related Symbol Documentation
operator [1/2]
template<class Thermo2T , template< class > class Type> Ostream & operator (Ostream & , const thermo2T< Thermo2T, Type > &) friend
operator [2/2]
template<class Thermo2T , template< class > class Type> Ostream & operator (Ostream & , const thermo2T< Thermo2T, Type > &) friend
operator* [1/2]
template<class Thermo2T , template< class > class Type> thermo2T operator* (const scalar s, const thermo2T< Thermo2T, Type > &) friend
operator* [2/2]
template<class Thermo2T , template< class > class Type> thermo2T operator* (const scalar s, const thermo2T< Thermo2T, Type > &) friend
operator+ [1/2]
template<class Thermo2T , template< class > class Type> thermo2T operator+ (const thermo2T< Thermo2T, Type > & , const thermo2T< Thermo2T, Type > &) friend
operator+ [2/2]
template<class Thermo2T , template< class > class Type> thermo2T operator+ (const thermo2T< Thermo2T, Type > & , const thermo2T< Thermo2T, Type > &) friend
operator== [1/2]
template<class Thermo2T , template< class > class Type> thermo2T operator== (const thermo2T< Thermo2T, Type > & , const thermo2T< Thermo2T, Type > &) friend
operator== [2/2]
template<class Thermo2T , template< class > class Type> thermo2T operator== (const thermo2T< Thermo2T, Type > & , const thermo2T< Thermo2T, Type > &) friend
The documentation for this class was generated from the following files:
lnInclude/thermo2T.H
thermo/thermo2T/thermo2T.H
lnInclude/thermo2T.C
lnInclude/thermo2TI.H
thermo/thermo2T/thermo2T.C
thermo/thermo2T/thermo2TI.H