neTCLib: Foam::he2TThermo< Basic2TThermo, MixtureType > Class Template Reference
Foam::he2TThermo< Basic2TThermo, MixtureType > Class Template Reference
#include <he2TThermo.H>
Public Member Functions
he2TThermo (const fvMesh &, const word &phaseName)
he2TThermo (const fvMesh &, const dictionary &, const word &phaseName)
he2TThermo (const fvMesh &, const word &phaseName, const word &dictionaryName)
virtual ~he2TThermo ()
virtual MixtureType::basicMixtureType & composition ()
virtual const MixtureType::basicMixtureType & composition () const
virtual word thermoName () const
virtual bool incompressible () const
virtual bool isochoric () const
virtual volScalarField & he ()
virtual const volScalarField & he () const
virtual tmp< volScalarField > he (const volScalarField &p, const volScalarField &TTR) const
virtual tmp< scalarField > he (const scalarField &p, const scalarField &TTR, const labelList &cells) const
virtual tmp< scalarField > he (const scalarField &p, const scalarField &TTR, const label patchi) const
virtual tmp< volScalarField > hc () const
virtual tmp< scalarField > THE_TR (const scalarField &h, const scalarField &p, const scalarField &TTR0, const labelList &cells) const
virtual tmp< scalarField > THE_TR (const scalarField &h, const scalarField &p, const scalarField &TTR0, const label patchi) const
virtual tmp< scalarField > TEH_Vib (const scalarField &h, const scalarField &p, const scalarField &TTR0, const scalarField &TVib0, const labelList &cells) const
virtual tmp< scalarField > TEH_Vib (const scalarField &h, const scalarField &p, const scalarField &TTR0, const scalarField &TVib0, const label patchi) const
virtual tmp< scalarField > CpTR (const scalarField &p, const scalarField &TTR, const label patchi) const
virtual tmp< scalarField > CpTR (const scalarField &p, const scalarField &TTR, const labelList &cells) const
virtual tmp< volScalarField > CpTR () const
virtual tmp< volScalarField > CvT () const
virtual tmp< scalarField > CvT (const scalarField &p, const scalarField &TTR, const label patchi) const
virtual tmp< volScalarField > CvR () const
virtual tmp< scalarField > CvR (const scalarField &p, const scalarField &TTR, const label patchi) const
virtual tmp< volScalarField > CvVib () const
virtual tmp< scalarField > CvVib (const scalarField &p, const scalarField &TTR, const scalarField &Tvib, const scalar ThetaVib, const label patchi) const
virtual tmp< scalarField > rhoEoS (const scalarField &p, const scalarField &TTR, const labelList &cells) const
virtual tmp< volScalarField > gamma () const
virtual tmp< scalarField > gamma (const scalarField &p, const scalarField &TTR, const label patchi) const
virtual tmp< scalarField > CpvTR (const scalarField &p, const scalarField &TTR, const label patchi) const
virtual tmp< volScalarField > CpvTR () const
virtual tmp< volScalarField > CpByCpvTR () const
virtual tmp< scalarField > CpByCpvTR (const scalarField &p, const scalarField &TTR, const label patchi) const
virtual tmp< volScalarField > W () const
virtual tmp< volScalarField > kappaTR () const
virtual tmp< scalarField > kappaTR (const label patchi) const
virtual tmp< volScalarField > kappaVib () const
virtual tmp< scalarField > kappaVib (const label patchi) const
virtual tmp< volScalarField > alphaheTR () const
virtual tmp< scalarField > alphaheTR (const label patchi) const
virtual tmp< volScalarField > kappaEff (const volScalarField &) const
virtual tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const
virtual tmp< volScalarField > alphaEff (const volScalarField &alphat) const
virtual tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const
virtual bool read ()
he2TThermo (const fvMesh &, const word &phaseName)
he2TThermo (const fvMesh &, const dictionary &, const word &phaseName)
he2TThermo (const fvMesh &, const word &phaseName, const word &dictionaryName)
virtual ~he2TThermo ()
virtual MixtureType::basicMixtureType & composition ()
virtual const MixtureType::basicMixtureType & composition () const
virtual word thermoName () const
virtual bool incompressible () const
virtual bool isochoric () const
virtual volScalarField & he ()
virtual const volScalarField & he () const
virtual tmp< volScalarField > he (const volScalarField &p, const volScalarField &TTR) const
virtual tmp< scalarField > he (const scalarField &p, const scalarField &TTR, const labelList &cells) const
virtual tmp< scalarField > he (const scalarField &p, const scalarField &TTR, const label patchi) const
virtual tmp< volScalarField > hc () const
virtual tmp< scalarField > THE_TR (const scalarField &h, const scalarField &p, const scalarField &TTR0, const labelList &cells) const
virtual tmp< scalarField > THE_TR (const scalarField &h, const scalarField &p, const scalarField &TTR0, const label patchi) const
virtual tmp< scalarField > TEH_Vib (const scalarField &h, const scalarField &p, const scalarField &TTR0, const scalarField &TVib0, const labelList &cells) const
virtual tmp< scalarField > TEH_Vib (const scalarField &h, const scalarField &p, const scalarField &TTR0, const scalarField &TVib0, const label patchi) const
virtual tmp< scalarField > CpTR (const scalarField &p, const scalarField &TTR, const label patchi) const
virtual tmp< scalarField > CpTR (const scalarField &p, const scalarField &TTR, const labelList &cells) const
virtual tmp< volScalarField > CpTR () const
virtual tmp< volScalarField > CvT () const
virtual tmp< scalarField > CvT (const scalarField &p, const scalarField &TTR, const label patchi) const
virtual tmp< volScalarField > CvR () const
virtual tmp< scalarField > CvR (const scalarField &p, const scalarField &TTR, const label patchi) const
virtual tmp< volScalarField > CvVib () const
virtual tmp< scalarField > CvVib (const scalarField &p, const scalarField &TTR, const scalarField &Tvib, const scalar ThetaVib, const label patchi) const
virtual tmp< scalarField > rhoEoS (const scalarField &p, const scalarField &TTR, const labelList &cells) const
virtual tmp< volScalarField > gamma () const
virtual tmp< scalarField > gamma (const scalarField &p, const scalarField &TTR, const label patchi) const
virtual tmp< scalarField > CpvTR (const scalarField &p, const scalarField &TTR, const label patchi) const
virtual tmp< volScalarField > CpvTR () const
virtual tmp< volScalarField > CpByCpvTR () const
virtual tmp< scalarField > CpByCpvTR (const scalarField &p, const scalarField &TTR, const label patchi) const
virtual tmp< volScalarField > W () const
virtual tmp< volScalarField > kappaTR () const
virtual tmp< scalarField > kappaTR (const label patchi) const
virtual tmp< volScalarField > kappaVib () const
virtual tmp< scalarField > kappaVib (const label patchi) const
virtual tmp< volScalarField > alphaheTR () const
virtual tmp< scalarField > alphaheTR (const label patchi) const
virtual tmp< volScalarField > kappaEff (const volScalarField &) const
virtual tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const
virtual tmp< volScalarField > alphaEff (const volScalarField &alphat) const
virtual tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const
virtual bool read ()
Protected Member Functions
void heBoundaryCorrection (volScalarField &he)
void heBoundaryCorrection (volScalarField &he)
Protected Attributes
volScalarField he_
Detailed Description
template<class Basic2TThermo, class MixtureType>
class Foam::he2TThermo< Basic2TThermo, MixtureType >
Definition at line 53 of file he2TThermo/he2TThermo.H.
Constructor & Destructor Documentation
he2TThermo() [1/6]
template<class Basic2TThermo , class MixtureType > Foam::he2TThermo< Basic2TThermo, MixtureType >::he2TThermo (const fvMesh & mesh, const word & phaseName)
Definition at line 104 of file he2TThermo/he2TThermo.C.
he2TThermo() [2/6]
template<class Basic2TThermo , class MixtureType > Foam::he2TThermo< Basic2TThermo, MixtureType >::he2TThermo (const fvMesh & mesh, const dictionary & dict, const word & phaseName)
Definition at line 137 of file he2TThermo/he2TThermo.C.
References Foam::he2TThermo< Basic2TThermo, MixtureType >::he_.
he2TThermo() [3/6]
template<class Basic2TThermo , class MixtureType > Foam::he2TThermo< Basic2TThermo, MixtureType >::he2TThermo (const fvMesh & mesh, const word & phaseName, const word & dictionaryName)
Definition at line 171 of file he2TThermo/he2TThermo.C.
~he2TThermo() [1/2]
template<class Basic2TThermo , class MixtureType > Foam::he2TThermo< Basic2TThermo, MixtureType >::~he2TThermo () virtual
Definition at line 208 of file he2TThermo/he2TThermo.C.
he2TThermo() [4/6]
template<class Basic2TThermo , class MixtureType > Foam::he2TThermo< Basic2TThermo, MixtureType >::he2TThermo (const fvMesh & , const word & phaseName)
he2TThermo() [5/6]
template<class Basic2TThermo , class MixtureType > Foam::he2TThermo< Basic2TThermo, MixtureType >::he2TThermo (const fvMesh & , const dictionary & , const word & phaseName)
he2TThermo() [6/6]
template<class Basic2TThermo , class MixtureType > Foam::he2TThermo< Basic2TThermo, MixtureType >::he2TThermo (const fvMesh & , const word & phaseName, const word & dictionaryName)
~he2TThermo() [2/2]
template<class Basic2TThermo , class MixtureType > virtual Foam::he2TThermo< Basic2TThermo, MixtureType >::~he2TThermo () virtual
Member Function Documentation
alphaEff() [1/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::alphaEff (const scalarField & alphat, const label patchi) const virtual
Definition at line 1078 of file he2TThermo/he2TThermo.C.
alphaEff() [2/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::alphaEff (const scalarField & alphat, const label patchi) const virtual
alphaEff() [3/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::alphaEff (const volScalarField & alphat) const virtual
Definition at line 1065 of file he2TThermo/he2TThermo.C.
alphaEff() [4/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::alphaEff (const volScalarField & alphat) const virtual
alphaheTR() [1/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::alphaheTR () const virtual
Definition at line 1005 of file he2TThermo/he2TThermo.C.
alphaheTR() [2/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::alphaheTR () const virtual
alphaheTR() [3/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::alphaheTR (const label patchi) const virtual
Definition at line 1015 of file he2TThermo/he2TThermo.C.
alphaheTR() [4/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::alphaheTR (const label patchi) const virtual
composition() [1/4]
template<class Basic2TThermo , class MixtureType > virtual MixtureType::basicMixtureType & Foam::he2TThermo< Basic2TThermo, MixtureType >::composition () inline virtual
Definition at line 128 of file he2TThermo/he2TThermo.H.
composition() [2/4]
template<class Basic2TThermo , class MixtureType > virtual MixtureType::basicMixtureType & Foam::he2TThermo< Basic2TThermo, MixtureType >::composition () inline virtual
Definition at line 128 of file lnInclude/he2TThermo.H.
composition() [3/4]
template<class Basic2TThermo , class MixtureType > virtual const MixtureType::basicMixtureType & Foam::he2TThermo< Basic2TThermo, MixtureType >::composition () const inline virtual
Definition at line 135 of file he2TThermo/he2TThermo.H.
composition() [4/4]
template<class Basic2TThermo , class MixtureType > virtual const MixtureType::basicMixtureType & Foam::he2TThermo< Basic2TThermo, MixtureType >::composition () const inline virtual
Definition at line 135 of file lnInclude/he2TThermo.H.
CpByCpvTR() [1/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CpByCpvTR () const virtual
Definition at line 771 of file he2TThermo/he2TThermo.C.
CpByCpvTR() [2/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CpByCpvTR () const virtual
CpByCpvTR() [3/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CpByCpvTR (const scalarField & p, const scalarField & TTR, const label patchi) const virtual
Definition at line 749 of file he2TThermo/he2TThermo.C.
CpByCpvTR() [4/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CpByCpvTR (const scalarField & p, const scalarField & TTR, const label patchi) const virtual
CpTR() [1/6]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CpTR () const virtual
Definition at line 385 of file he2TThermo/he2TThermo.C.
CpTR() [2/6]
template<class Basic2TThermo , class MixtureType > virtual tmp< volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CpTR () const virtual
CpTR() [3/6]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CpTR (const scalarField & p, const scalarField & TTR, const label patchi) const virtual
Definition at line 341 of file he2TThermo/he2TThermo.C.
CpTR() [4/6]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CpTR (const scalarField & p, const scalarField & TTR, const label patchi) const virtual
CpTR() [5/6]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CpTR (const scalarField & p, const scalarField & TTR, const labelList & cells) const virtual
Definition at line 363 of file he2TThermo/he2TThermo.C.
CpTR() [6/6]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CpTR (const scalarField & p, const scalarField & TTR, const labelList & cells) const virtual
CpvTR() [1/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CpvTR () const virtual
Definition at line 710 of file he2TThermo/he2TThermo.C.
CpvTR() [2/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CpvTR () const virtual
CpvTR() [3/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CpvTR (const scalarField & p, const scalarField & TTR, const label patchi) const virtual
Definition at line 688 of file he2TThermo/he2TThermo.C.
CpvTR() [4/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CpvTR (const scalarField & p, const scalarField & TTR, const label patchi) const virtual
CvR() [1/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CvR () const virtual
Definition at line 549 of file he2TThermo/he2TThermo.C.
References CvR().
CvR() [2/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CvR () const virtual
CvR() [3/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CvR (const scalarField & p, const scalarField & TTR, const label patchi) const virtual
Definition at line 446 of file he2TThermo/he2TThermo.C.
CvR() [4/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CvR (const scalarField & p, const scalarField & TTR, const label patchi) const virtual
CvT() [1/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CvT () const virtual
Definition at line 513 of file he2TThermo/he2TThermo.C.
References CvT().
CvT() [2/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CvT () const virtual
CvT() [3/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CvT (const scalarField & p, const scalarField & TTR, const label patchi) const virtual
Definition at line 425 of file he2TThermo/he2TThermo.C.
CvT() [4/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CvT (const scalarField & p, const scalarField & TTR, const label patchi) const virtual
CvVib() [1/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CvVib () const virtual
Definition at line 585 of file he2TThermo/he2TThermo.C.
References CvVib().
CvVib() [2/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CvVib () const virtual
CvVib() [3/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CvVib (const scalarField & p, const scalarField & TTR, const scalarField & Tvib, const scalar ThetaVib, const label patchi) const virtual
Definition at line 467 of file he2TThermo/he2TThermo.C.
CvVib() [4/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::CvVib (const scalarField & p, const scalarField & TTR, const scalarField & Tvib, const scalar ThetaVib, const label patchi) const virtual
gamma() [1/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::gamma () const virtual
Definition at line 646 of file he2TThermo/he2TThermo.C.
gamma() [2/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::gamma () const virtual
gamma() [3/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::gamma (const scalarField & p, const scalarField & TTR, const label patchi) const virtual
Definition at line 624 of file he2TThermo/he2TThermo.C.
gamma() [4/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::gamma (const scalarField & p, const scalarField & TTR, const label patchi) const virtual
hc() [1/2]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::hc () const virtual
Definition at line 304 of file he2TThermo/he2TThermo.C.
hc() [2/2]
template<class Basic2TThermo , class MixtureType > virtual tmp< volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::hc () const virtual
he() [1/10]
template<class Basic2TThermo , class MixtureType > virtual volScalarField & Foam::he2TThermo< Basic2TThermo, MixtureType >::he () inline virtual
Definition at line 165 of file he2TThermo/he2TThermo.H.
References Foam::he2TThermo< Basic2TThermo, MixtureType >::he_.
he() [2/10]
template<class Basic2TThermo , class MixtureType > virtual volScalarField & Foam::he2TThermo< Basic2TThermo, MixtureType >::he () inline virtual
Definition at line 165 of file lnInclude/he2TThermo.H.
References Foam::he2TThermo< Basic2TThermo, MixtureType >::he_.
he() [3/10]
template<class Basic2TThermo , class MixtureType > virtual const volScalarField & Foam::he2TThermo< Basic2TThermo, MixtureType >::he () const inline virtual
Definition at line 171 of file he2TThermo/he2TThermo.H.
References Foam::he2TThermo< Basic2TThermo, MixtureType >::he_.
he() [4/10]
template<class Basic2TThermo , class MixtureType > virtual const volScalarField & Foam::he2TThermo< Basic2TThermo, MixtureType >::he () const inline virtual
Definition at line 171 of file lnInclude/he2TThermo.H.
References Foam::he2TThermo< Basic2TThermo, MixtureType >::he_.
he() [5/10]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::he (const scalarField & p, const scalarField & TTR, const label patchi) const virtual
Definition at line 282 of file he2TThermo/he2TThermo.C.
he() [6/10]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::he (const scalarField & p, const scalarField & TTR, const label patchi) const virtual
he() [7/10]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::he (const scalarField & p, const scalarField & TTR, const labelList & cells) const virtual
Definition at line 262 of file he2TThermo/he2TThermo.C.
he() [8/10]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::he (const scalarField & p, const scalarField & TTR, const labelList & cells) const virtual
he() [9/10]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::he (const volScalarField & p, const volScalarField & TTR) const virtual
Definition at line 215 of file he2TThermo/he2TThermo.C.
he() [10/10]
template<class Basic2TThermo , class MixtureType > virtual tmp< volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::he (const volScalarField & p, const volScalarField & TTR) const virtual
heBoundaryCorrection() [1/2]
template<class Basic2TThermo , class MixtureType > void Foam::he2TThermo< Basic2TThermo, MixtureType >::heBoundaryCorrection (volScalarField & he) protected
Definition at line 36 of file he2TThermo/he2TThermo.C.
heBoundaryCorrection() [2/2]
template<class Basic2TThermo , class MixtureType > void Foam::he2TThermo< Basic2TThermo, MixtureType >::heBoundaryCorrection (volScalarField & he) protected
incompressible() [1/2]
template<class Basic2TThermo , class MixtureType > virtual bool Foam::he2TThermo< Basic2TThermo, MixtureType >::incompressible () const inline virtual
Definition at line 148 of file he2TThermo/he2TThermo.H.
incompressible() [2/2]
template<class Basic2TThermo , class MixtureType > virtual bool Foam::he2TThermo< Basic2TThermo, MixtureType >::incompressible () const inline virtual
Definition at line 148 of file lnInclude/he2TThermo.H.
isochoric() [1/2]
template<class Basic2TThermo , class MixtureType > virtual bool Foam::he2TThermo< Basic2TThermo, MixtureType >::isochoric () const inline virtual
Definition at line 155 of file he2TThermo/he2TThermo.H.
isochoric() [2/2]
template<class Basic2TThermo , class MixtureType > virtual bool Foam::he2TThermo< Basic2TThermo, MixtureType >::isochoric () const inline virtual
Definition at line 155 of file lnInclude/he2TThermo.H.
kappaEff() [1/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::kappaEff (const scalarField & alphat, const label patchi) const virtual
Definition at line 1043 of file he2TThermo/he2TThermo.C.
References CpTR().
kappaEff() [2/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::kappaEff (const scalarField & alphat, const label patchi) const virtual
kappaEff() [3/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::kappaEff (const volScalarField & alphat) const virtual
Definition at line 1030 of file he2TThermo/he2TThermo.C.
References CpTR().
kappaEff() [4/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::kappaEff (const volScalarField &) const virtual
kappaTR() [1/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::kappaTR () const virtual
Definition at line 954 of file he2TThermo/he2TThermo.C.
References CpTR().
kappaTR() [2/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::kappaTR () const virtual
kappaTR() [3/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::kappaTR (const label patchi) const virtual
Definition at line 963 of file he2TThermo/he2TThermo.C.
References CpTR().
kappaTR() [4/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::kappaTR (const label patchi) const virtual
kappaVib() [1/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::kappaVib () const virtual
Definition at line 979 of file he2TThermo/he2TThermo.C.
References CpTR().
kappaVib() [2/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::kappaVib () const virtual
kappaVib() [3/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::kappaVib (const label patchi) const virtual
Definition at line 988 of file he2TThermo/he2TThermo.C.
References CpTR().
kappaVib() [4/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::kappaVib (const label patchi) const virtual
read() [1/2]
template<class Basic2TThermo , class MixtureType > bool Foam::he2TThermo< Basic2TThermo, MixtureType >::read () virtual
Definition at line 1099 of file he2TThermo/he2TThermo.C.
read() [2/2]
template<class Basic2TThermo , class MixtureType > virtual bool Foam::he2TThermo< Basic2TThermo, MixtureType >::read () virtual
rhoEoS() [1/2]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::rhoEoS (const scalarField & p, const scalarField & TTR, const labelList & cells) const virtual
Definition at line 491 of file he2TThermo/he2TThermo.C.
rhoEoS() [2/2]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::rhoEoS (const scalarField & p, const scalarField & TTR, const labelList & cells) const virtual
TEH_Vib() [1/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::TEH_Vib (const scalarField & h, const scalarField & p, const scalarField & TTR0, const scalarField & TVib0, const label patchi) const virtual
Definition at line 888 of file he2TThermo/he2TThermo.C.
TEH_Vib() [2/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::TEH_Vib (const scalarField & h, const scalarField & p, const scalarField & TTR0, const scalarField & TVib0, const label patchi) const virtual
TEH_Vib() [3/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::TEH_Vib (const scalarField & h, const scalarField & p, const scalarField & TTR0, const scalarField & TVib0, const labelList & cells) const virtual
Definition at line 864 of file he2TThermo/he2TThermo.C.
TEH_Vib() [4/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::TEH_Vib (const scalarField & h, const scalarField & p, const scalarField & TTR0, const scalarField & TVib0, const labelList & cells) const virtual
THE_TR() [1/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::THE_TR (const scalarField & h, const scalarField & p, const scalarField & TTR0, const label patchi) const virtual
Definition at line 839 of file he2TThermo/he2TThermo.C.
THE_TR() [2/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::THE_TR (const scalarField & h, const scalarField & p, const scalarField & TTR0, const label patchi) const virtual
THE_TR() [3/4]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::THE_TR (const scalarField & h, const scalarField & p, const scalarField & TTR0, const labelList & cells) const virtual
Definition at line 817 of file he2TThermo/he2TThermo.C.
THE_TR() [4/4]
template<class Basic2TThermo , class MixtureType > virtual tmp< scalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::THE_TR (const scalarField & h, const scalarField & p, const scalarField & TTR0, const labelList & cells) const virtual
thermoName() [1/2]
template<class Basic2TThermo , class MixtureType > virtual word Foam::he2TThermo< Basic2TThermo, MixtureType >::thermoName () const inline virtual
Definition at line 141 of file he2TThermo/he2TThermo.H.
thermoName() [2/2]
template<class Basic2TThermo , class MixtureType > virtual word Foam::he2TThermo< Basic2TThermo, MixtureType >::thermoName () const inline virtual
Definition at line 141 of file lnInclude/he2TThermo.H.
W() [1/2]
template<class Basic2TThermo , class MixtureType > Foam::tmp< Foam::volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::W () const virtual
Definition at line 915 of file he2TThermo/he2TThermo.C.
W() [2/2]
template<class Basic2TThermo , class MixtureType > virtual tmp< volScalarField > Foam::he2TThermo< Basic2TThermo, MixtureType >::W () const virtual
Member Data Documentation
he_
template<class Basic2TThermo , class MixtureType > volScalarField Foam::he2TThermo< Basic2TThermo, MixtureType >::he_ protected
Definition at line 63 of file he2TThermo/he2TThermo.H.
Referenced by Foam::he2TThermo< Basic2TThermo, MixtureType >::he(), Foam::he2TThermo< Basic2TThermo, MixtureType >::he(), and Foam::he2TThermo< Basic2TThermo, MixtureType >::he2TThermo().
The documentation for this class was generated from the following files:
he2TThermo/he2TThermo.H
lnInclude/he2TThermo.H
he2TThermo/he2TThermo.C
lnInclude/he2TThermo.C