neTCLib: Foam::basic2TThermo Class Reference
Foam::basic2TThermo Class Reference abstract
#include <basic2TThermo.H>
Public Member Functions
declareRunTimeSelectionTable (autoPtr, basic2TThermo, fvMesh,(const fvMesh &mesh, const word &phaseName),(mesh, phaseName))
declareRunTimeSelectionTable (autoPtr, basic2TThermo, fvMeshDictPhase,(const fvMesh &mesh, const word &phaseName, const word &dictName),(mesh, phaseName, dictName))
basic2TThermo (const fvMesh &, const word &phaseName)
basic2TThermo (const fvMesh &, const dictionary &, const word &phaseName)
basic2TThermo (const fvMesh &, const word &phaseName, const word &dictionaryName)
virtual ~basic2TThermo ()
word phasePropertyName (const word &name) const
word phaseScopedName (const std::string &scope, const word &name) const
void validate (const string &app, const word &) const
void validate (const string &app, const word &, const word &) const
void validate (const string &app, const word &, const word &, const word &) const
void validate (const string &app, const word &, const word &, const word &, const word &) const
virtual void correct ()=0
virtual word thermoName () const =0
virtual bool incompressible () const =0
virtual bool isochoric () const =0
bool dpdt () const noexcept
bool updateTTR () const noexcept
bool updateTVib () const noexcept
virtual volScalarField & p ()
virtual const volScalarField & p () const
virtual tmp< volScalarField > rho () const =0
virtual tmp< scalarField > rho (const label patchi) const =0
virtual volScalarField & he ()=0
virtual const volScalarField & he () const =0
virtual tmp< volScalarField > he (const volScalarField &p, const volScalarField &TTR) const =0
virtual tmp< scalarField > he (const scalarField &p, const scalarField &TTR, const labelList &cells) const =0
virtual tmp< scalarField > he (const scalarField &p, const scalarField &TTR, const label patchi) const =0
virtual tmp< volScalarField > hc () const =0
virtual tmp< scalarField > THE_TR (const scalarField &h, const scalarField &p, const scalarField &TTR0, const labelList &cells) const =0
virtual tmp< scalarField > THE_TR (const scalarField &h, const scalarField &p, const scalarField &TTR0, const label patchi) const =0
virtual tmp< scalarField > TEH_Vib (const scalarField &esVib, const scalarField &p, const scalarField &TTR0, const scalarField &TVib0, const labelList &cells) const =0
virtual tmp< scalarField > TEH_Vib (const scalarField &esVib, const scalarField &p, const scalarField &TTR0, const scalarField &TVib0, const label patchi) const =0
virtual const volScalarField & TTR () const
virtual const volScalarField & TVib () const
virtual volScalarField & TTR ()
virtual volScalarField & TVib ()
virtual tmp< volScalarField > CpTR () const =0
virtual tmp< scalarField > CpTR (const scalarField &p, const scalarField &TTR, const label patchi) const =0
virtual tmp< scalarField > CpTR (const scalarField &p, const scalarField &TTR, const labelList &cells) const =0
virtual tmp< volScalarField > CvT () const =0
virtual tmp< scalarField > CvT (const scalarField &p, const scalarField &TTR, const label patchi) const =0
virtual tmp< volScalarField > CvR () const =0
virtual tmp< scalarField > CvR (const scalarField &p, const scalarField &TTR, const label patchi) const =0
virtual tmp< volScalarField > CvVib () const =0
virtual tmp< scalarField > CvVib (const scalarField &p, const scalarField &TTR, const scalarField &Tvib, const scalar ThetaVib, const label patchi) const =0
virtual tmp< scalarField > rhoEoS (const scalarField &p, const scalarField &TTR, const labelList &cells) const =0
virtual tmp< volScalarField > gamma () const =0
virtual tmp< scalarField > gamma (const scalarField &p, const scalarField &TTR, const label patchi) const =0
virtual tmp< volScalarField > CpvTR () const =0
virtual tmp< scalarField > CpvTR (const scalarField &p, const scalarField &TTR, const label patchi) const =0
virtual tmp< volScalarField > CpByCpvTR () const =0
virtual tmp< scalarField > CpByCpvTR (const scalarField &p, const scalarField &TTR, const label patchi) const =0
virtual tmp< volScalarField > W () const =0
virtual const volScalarField & alpha () const
virtual const scalarField & alpha (const label patchi) const
virtual tmp< volScalarField > kappaTR () const =0
virtual tmp< scalarField > kappaTR (const label patchi) const =0
virtual tmp< volScalarField > kappaVib () const =0
virtual tmp< scalarField > kappaVib (const label patchi) const =0
virtual tmp< volScalarField > alphaheTR () const =0
virtual tmp< scalarField > alphaheTR (const label patchi) const =0
virtual tmp< volScalarField > kappaEff (const volScalarField &) const =0
virtual tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const =0
virtual tmp< volScalarField > alphaEff (const volScalarField &alphat) const =0
virtual tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const =0
virtual bool read ()
declareRunTimeSelectionTable (autoPtr, basic2TThermo, fvMesh,(const fvMesh &mesh, const word &phaseName),(mesh, phaseName))
declareRunTimeSelectionTable (autoPtr, basic2TThermo, fvMeshDictPhase,(const fvMesh &mesh, const word &phaseName, const word &dictName),(mesh, phaseName, dictName))
basic2TThermo (const fvMesh &, const word &phaseName)
basic2TThermo (const fvMesh &, const dictionary &, const word &phaseName)
basic2TThermo (const fvMesh &, const word &phaseName, const word &dictionaryName)
virtual ~basic2TThermo ()
word phasePropertyName (const word &name) const
word phaseScopedName (const std::string &scope, const word &name) const
void validate (const string &app, const word &) const
void validate (const string &app, const word &, const word &) const
void validate (const string &app, const word &, const word &, const word &) const
void validate (const string &app, const word &, const word &, const word &, const word &) const
virtual void correct ()=0
virtual word thermoName () const =0
virtual bool incompressible () const =0
virtual bool isochoric () const =0
bool dpdt () const noexcept
bool updateTTR () const noexcept
bool updateTVib () const noexcept
virtual volScalarField & p ()
virtual const volScalarField & p () const
virtual tmp< volScalarField > rho () const =0
virtual tmp< scalarField > rho (const label patchi) const =0
virtual volScalarField & he ()=0
virtual const volScalarField & he () const =0
virtual tmp< volScalarField > he (const volScalarField &p, const volScalarField &TTR) const =0
virtual tmp< scalarField > he (const scalarField &p, const scalarField &TTR, const labelList &cells) const =0
virtual tmp< scalarField > he (const scalarField &p, const scalarField &TTR, const label patchi) const =0
virtual tmp< volScalarField > hc () const =0
virtual tmp< scalarField > THE_TR (const scalarField &h, const scalarField &p, const scalarField &TTR0, const labelList &cells) const =0
virtual tmp< scalarField > THE_TR (const scalarField &h, const scalarField &p, const scalarField &TTR0, const label patchi) const =0
virtual tmp< scalarField > TEH_Vib (const scalarField &esVib, const scalarField &p, const scalarField &TTR0, const scalarField &TVib0, const labelList &cells) const =0
virtual tmp< scalarField > TEH_Vib (const scalarField &esVib, const scalarField &p, const scalarField &TTR0, const scalarField &TVib0, const label patchi) const =0
virtual const volScalarField & TTR () const
virtual const volScalarField & TVib () const
virtual volScalarField & TTR ()
virtual volScalarField & TVib ()
virtual tmp< volScalarField > CpTR () const =0
virtual tmp< scalarField > CpTR (const scalarField &p, const scalarField &TTR, const label patchi) const =0
virtual tmp< scalarField > CpTR (const scalarField &p, const scalarField &TTR, const labelList &cells) const =0
virtual tmp< volScalarField > CvT () const =0
virtual tmp< scalarField > CvT (const scalarField &p, const scalarField &TTR, const label patchi) const =0
virtual tmp< volScalarField > CvR () const =0
virtual tmp< scalarField > CvR (const scalarField &p, const scalarField &TTR, const label patchi) const =0
virtual tmp< volScalarField > CvVib () const =0
virtual tmp< scalarField > CvVib (const scalarField &p, const scalarField &TTR, const scalarField &Tvib, const scalar ThetaVib, const label patchi) const =0
virtual tmp< scalarField > rhoEoS (const scalarField &p, const scalarField &TTR, const labelList &cells) const =0
virtual tmp< volScalarField > gamma () const =0
virtual tmp< scalarField > gamma (const scalarField &p, const scalarField &TTR, const label patchi) const =0
virtual tmp< volScalarField > CpvTR () const =0
virtual tmp< scalarField > CpvTR (const scalarField &p, const scalarField &TTR, const label patchi) const =0
virtual tmp< volScalarField > CpByCpvTR () const =0
virtual tmp< scalarField > CpByCpvTR (const scalarField &p, const scalarField &TTR, const label patchi) const =0
virtual tmp< volScalarField > W () const =0
virtual const volScalarField & alpha () const
virtual const scalarField & alpha (const label patchi) const
virtual tmp< volScalarField > kappaTR () const =0
virtual tmp< scalarField > kappaTR (const label patchi) const =0
virtual tmp< volScalarField > kappaVib () const =0
virtual tmp< scalarField > kappaVib (const label patchi) const =0
virtual tmp< volScalarField > alphaheTR () const =0
virtual tmp< scalarField > alphaheTR (const label patchi) const =0
virtual tmp< volScalarField > kappaEff (const volScalarField &) const =0
virtual tmp< scalarField > kappaEff (const scalarField &alphat, const label patchi) const =0
virtual tmp< volScalarField > alphaEff (const volScalarField &alphat) const =0
virtual tmp< scalarField > alphaEff (const scalarField &alphat, const label patchi) const =0
virtual bool read ()
template<class TThermo >
Foam::autoPtr< TThermo > New (const fvMesh &mesh, const word &phaseName)
template<class TThermo >
Foam::autoPtr< TThermo > New (const fvMesh &mesh, const dictionary &dict, const word &phaseName)
template<class TThermo >
Foam::autoPtr< TThermo > New (const fvMesh &mesh, const word &phaseName, const word &dictName)
Static Public Member Functions
template<class Thermo >
static autoPtr< Thermo > New (const fvMesh &, const word &phaseName=word::null)
template<class Thermo >
static autoPtr< Thermo > New (const fvMesh &, const dictionary &, const word &phaseName=word::null)
template<class Thermo >
static autoPtr< Thermo > New (const fvMesh &, const word &phaseName, const word &dictName)
static autoPtr< basic2TThermo > New (const fvMesh &, const word &phaseName=word::null)
static word phasePropertyName (const word &name, const word &phaseName)
static const basic2TThermo & lookupThermo (const fvPatchScalarField &pf)
static Ostream & printThermoNames (Ostream &os, const wordList &cmptNames, const wordList &thermoNames)
static wordList splitThermoName (const std::string &thermoName, const int nExpectedCmpts)
template<class Thermo >
static autoPtr< Thermo > New (const fvMesh &, const word &phaseName=word::null)
template<class Thermo >
static autoPtr< Thermo > New (const fvMesh &, const dictionary &, const word &phaseName=word::null)
template<class Thermo >
static autoPtr< Thermo > New (const fvMesh &, const word &phaseName, const word &dictName)
static autoPtr< basic2TThermo > New (const fvMesh &, const word &phaseName=word::null)
static word phasePropertyName (const word &name, const word &phaseName)
static const basic2TThermo & lookupThermo (const fvPatchScalarField &pf)
static Ostream & printThermoNames (Ostream &os, const wordList &cmptNames, const wordList &thermoNames)
static wordList splitThermoName (const std::string &thermoName, const int nExpectedCmpts)
Static Public Attributes
static const word dictName
Protected Member Functions
wordList heBoundaryTypes ()
wordList heBoundaryBaseTypes ()
basic2TThermo (const basic2TThermo &)=delete
wordList heBoundaryTypes ()
wordList heBoundaryBaseTypes ()
basic2TThermo (const basic2TThermo &)=delete
Protected Attributes
const word & phaseName_
bool pOwner_
bool TOwnerTR_
bool TOwnerVib_
bool dpdt_
volScalarField & p_
volScalarField & TTR_
volScalarField & TVib_
volScalarField alpha_
Detailed Description
Definition at line 64 of file basic2TThermo/basic2TThermo.H.
Constructor & Destructor Documentation
basic2TThermo() [1/8]
Foam::basic2TThermo::basic2TThermo (const basic2TThermo &) protected delete
basic2TThermo() [2/8]
Foam::basic2TThermo::basic2TThermo (const fvMesh & mesh, const word & phaseName)
Definition at line 275 of file basic2TThermo/basic2TThermo.C.
References TOwnerTR_, and TOwnerVib_.
basic2TThermo() [3/8]
Foam::basic2TThermo::basic2TThermo (const fvMesh & mesh, const dictionary & dict, const word & phaseName)
Definition at line 325 of file basic2TThermo/basic2TThermo.C.
References TOwnerTR_, and TOwnerVib_.
basic2TThermo() [4/8]
Foam::basic2TThermo::basic2TThermo (const fvMesh & mesh, const word & phaseName, const word & dictionaryName)
Definition at line 377 of file basic2TThermo/basic2TThermo.C.
References alpha_, TOwnerTR_, and TTR_.
~basic2TThermo() [1/2]
Foam::basic2TThermo::~basic2TThermo () virtual
Definition at line 452 of file basic2TThermo/basic2TThermo.C.
basic2TThermo() [5/8]
Foam::basic2TThermo::basic2TThermo (const basic2TThermo &) protected delete
basic2TThermo() [6/8]
Foam::basic2TThermo::basic2TThermo (const fvMesh & , const word & phaseName)
basic2TThermo() [7/8]
Foam::basic2TThermo::basic2TThermo (const fvMesh & , const dictionary & , const word & phaseName)
basic2TThermo() [8/8]
Foam::basic2TThermo::basic2TThermo (const fvMesh & , const word & phaseName, const word & dictionaryName)
~basic2TThermo() [2/2]
virtual Foam::basic2TThermo::~basic2TThermo () virtual
Member Function Documentation
alpha() [1/4]
const Foam::volScalarField & Foam::basic2TThermo::alpha () const virtual
Definition at line 662 of file basic2TThermo/basic2TThermo.C.
alpha() [2/4]
virtual const volScalarField & Foam::basic2TThermo::alpha () const virtual
alpha() [3/4]
const Foam::scalarField & Foam::basic2TThermo::alpha (const label patchi) const virtual
Definition at line 668 of file basic2TThermo/basic2TThermo.C.
alpha() [4/4]
virtual const scalarField & Foam::basic2TThermo::alpha (const label patchi) const virtual
alphaEff() [1/4]
virtual tmp< scalarField > Foam::basic2TThermo::alphaEff (const scalarField & alphat, const label patchi) const pure virtual
alphaEff() [2/4]
virtual tmp< scalarField > Foam::basic2TThermo::alphaEff (const scalarField & alphat, const label patchi) const pure virtual
alphaEff() [3/4]
virtual tmp< volScalarField > Foam::basic2TThermo::alphaEff (const volScalarField & alphat) const pure virtual
alphaEff() [4/4]
virtual tmp< volScalarField > Foam::basic2TThermo::alphaEff (const volScalarField & alphat) const pure virtual
alphaheTR() [1/4]
virtual tmp< volScalarField > Foam::basic2TThermo::alphaheTR () const pure virtual
alphaheTR() [2/4]
virtual tmp< volScalarField > Foam::basic2TThermo::alphaheTR () const pure virtual
alphaheTR() [3/4]
virtual tmp< scalarField > Foam::basic2TThermo::alphaheTR (const label patchi) const pure virtual
alphaheTR() [4/4]
virtual tmp< scalarField > Foam::basic2TThermo::alphaheTR (const label patchi) const pure virtual
correct() [1/2]
virtual void Foam::basic2TThermo::correct () pure virtual
correct() [2/2]
virtual void Foam::basic2TThermo::correct () pure virtual
CpByCpvTR() [1/4]
virtual tmp< volScalarField > Foam::basic2TThermo::CpByCpvTR () const pure virtual
CpByCpvTR() [2/4]
virtual tmp< volScalarField > Foam::basic2TThermo::CpByCpvTR () const pure virtual
CpByCpvTR() [3/4]
virtual tmp< scalarField > Foam::basic2TThermo::CpByCpvTR (const scalarField & p, const scalarField & TTR, const label patchi) const pure virtual
CpByCpvTR() [4/4]
virtual tmp< scalarField > Foam::basic2TThermo::CpByCpvTR (const scalarField & p, const scalarField & TTR, const label patchi) const pure virtual
CpTR() [1/6]
virtual tmp< volScalarField > Foam::basic2TThermo::CpTR () const pure virtual
CpTR() [2/6]
virtual tmp< volScalarField > Foam::basic2TThermo::CpTR () const pure virtual
CpTR() [3/6]
virtual tmp< scalarField > Foam::basic2TThermo::CpTR (const scalarField & p, const scalarField & TTR, const label patchi) const pure virtual
CpTR() [4/6]
virtual tmp< scalarField > Foam::basic2TThermo::CpTR (const scalarField & p, const scalarField & TTR, const label patchi) const pure virtual
CpTR() [5/6]
virtual tmp< scalarField > Foam::basic2TThermo::CpTR (const scalarField & p, const scalarField & TTR, const labelList & cells) const pure virtual
CpTR() [6/6]
virtual tmp< scalarField > Foam::basic2TThermo::CpTR (const scalarField & p, const scalarField & TTR, const labelList & cells) const pure virtual
CpvTR() [1/4]
virtual tmp< volScalarField > Foam::basic2TThermo::CpvTR () const pure virtual
CpvTR() [2/4]
virtual tmp< volScalarField > Foam::basic2TThermo::CpvTR () const pure virtual
CpvTR() [3/4]
virtual tmp< scalarField > Foam::basic2TThermo::CpvTR (const scalarField & p, const scalarField & TTR, const label patchi) const pure virtual
CpvTR() [4/4]
virtual tmp< scalarField > Foam::basic2TThermo::CpvTR (const scalarField & p, const scalarField & TTR, const label patchi) const pure virtual
CvR() [1/4]
virtual tmp< volScalarField > Foam::basic2TThermo::CvR () const pure virtual
CvR() [2/4]
virtual tmp< volScalarField > Foam::basic2TThermo::CvR () const pure virtual
CvR() [3/4]
virtual tmp< scalarField > Foam::basic2TThermo::CvR (const scalarField & p, const scalarField & TTR, const label patchi) const pure virtual
CvR() [4/4]
virtual tmp< scalarField > Foam::basic2TThermo::CvR (const scalarField & p, const scalarField & TTR, const label patchi) const pure virtual
CvT() [1/4]
virtual tmp< volScalarField > Foam::basic2TThermo::CvT () const pure virtual
CvT() [2/4]
virtual tmp< volScalarField > Foam::basic2TThermo::CvT () const pure virtual
CvT() [3/4]
virtual tmp< scalarField > Foam::basic2TThermo::CvT (const scalarField & p, const scalarField & TTR, const label patchi) const pure virtual
CvT() [4/4]
virtual tmp< scalarField > Foam::basic2TThermo::CvT (const scalarField & p, const scalarField & TTR, const label patchi) const pure virtual
CvVib() [1/4]
virtual tmp< volScalarField > Foam::basic2TThermo::CvVib () const pure virtual
CvVib() [2/4]
virtual tmp< volScalarField > Foam::basic2TThermo::CvVib () const pure virtual
CvVib() [3/4]
virtual tmp< scalarField > Foam::basic2TThermo::CvVib (const scalarField & p, const scalarField & TTR, const scalarField & Tvib, const scalar ThetaVib, const label patchi) const pure virtual
CvVib() [4/4]
virtual tmp< scalarField > Foam::basic2TThermo::CvVib (const scalarField & p, const scalarField & TTR, const scalarField & Tvib, const scalar ThetaVib, const label patchi) const pure virtual
declareRunTimeSelectionTable() [1/4]
Foam::basic2TThermo::declareRunTimeSelectionTable (autoPtr , basic2TThermo , fvMesh , (const fvMesh &mesh, const word &phaseName) , (mesh, phaseName))
declareRunTimeSelectionTable() [2/4]
Foam::basic2TThermo::declareRunTimeSelectionTable (autoPtr , basic2TThermo , fvMesh , (const fvMesh &mesh, const word &phaseName) , (mesh, phaseName))
declareRunTimeSelectionTable() [3/4]
Foam::basic2TThermo::declareRunTimeSelectionTable (autoPtr , basic2TThermo , fvMeshDictPhase , (const fvMesh &mesh, const word &phaseName, const word &dictName) , (mesh, phaseName, dictName))
declareRunTimeSelectionTable() [4/4]
Foam::basic2TThermo::declareRunTimeSelectionTable (autoPtr , basic2TThermo , fvMeshDictPhase , (const fvMesh &mesh, const word &phaseName, const word &dictName) , (mesh, phaseName, dictName))
dpdt() [1/2]
bool Foam::basic2TThermo::dpdt () const inline noexcept
Definition at line 364 of file basic2TThermo/basic2TThermo.H.
References dpdt_.
dpdt() [2/2]
bool Foam::basic2TThermo::dpdt () const inline noexcept
Definition at line 364 of file lnInclude/basic2TThermo.H.
References dpdt_.
gamma() [1/4]
virtual tmp< volScalarField > Foam::basic2TThermo::gamma () const pure virtual
gamma() [2/4]
virtual tmp< volScalarField > Foam::basic2TThermo::gamma () const pure virtual
gamma() [3/4]
virtual tmp< scalarField > Foam::basic2TThermo::gamma (const scalarField & p, const scalarField & TTR, const label patchi) const pure virtual
gamma() [4/4]
virtual tmp< scalarField > Foam::basic2TThermo::gamma (const scalarField & p, const scalarField & TTR, const label patchi) const pure virtual
hc() [1/2]
virtual tmp< volScalarField > Foam::basic2TThermo::hc () const pure virtual
hc() [2/2]
virtual tmp< volScalarField > Foam::basic2TThermo::hc () const pure virtual
he() [1/10]
virtual const volScalarField & Foam::basic2TThermo::he () const pure virtual
he() [2/10]
virtual const volScalarField & Foam::basic2TThermo::he () const pure virtual
he() [3/10]
virtual volScalarField & Foam::basic2TThermo::he () pure virtual
he() [4/10]
virtual volScalarField & Foam::basic2TThermo::he () pure virtual
he() [5/10]
virtual tmp< scalarField > Foam::basic2TThermo::he (const scalarField & p, const scalarField & TTR, const label patchi) const pure virtual
he() [6/10]
virtual tmp< scalarField > Foam::basic2TThermo::he (const scalarField & p, const scalarField & TTR, const label patchi) const pure virtual
he() [7/10]
virtual tmp< scalarField > Foam::basic2TThermo::he (const scalarField & p, const scalarField & TTR, const labelList & cells) const pure virtual
he() [8/10]
virtual tmp< scalarField > Foam::basic2TThermo::he (const scalarField & p, const scalarField & TTR, const labelList & cells) const pure virtual
he() [9/10]
virtual tmp< volScalarField > Foam::basic2TThermo::he (const volScalarField & p, const volScalarField & TTR) const pure virtual
he() [10/10]
virtual tmp< volScalarField > Foam::basic2TThermo::he (const volScalarField & p, const volScalarField & TTR) const pure virtual
heBoundaryBaseTypes() [1/2]
Foam::wordList Foam::basic2TThermo::heBoundaryBaseTypes () protected
Definition at line 164 of file basic2TThermo/basic2TThermo.C.
heBoundaryBaseTypes() [2/2]
wordList Foam::basic2TThermo::heBoundaryBaseTypes () protected
heBoundaryTypes() [1/2]
Foam::wordList Foam::basic2TThermo::heBoundaryTypes () protected
Definition at line 198 of file basic2TThermo/basic2TThermo.C.
heBoundaryTypes() [2/2]
wordList Foam::basic2TThermo::heBoundaryTypes () protected
incompressible() [1/2]
virtual bool Foam::basic2TThermo::incompressible () const pure virtual
incompressible() [2/2]
virtual bool Foam::basic2TThermo::incompressible () const pure virtual
isochoric() [1/2]
virtual bool Foam::basic2TThermo::isochoric () const pure virtual
isochoric() [2/2]
virtual bool Foam::basic2TThermo::isochoric () const pure virtual
kappaEff() [1/4]
virtual tmp< scalarField > Foam::basic2TThermo::kappaEff (const scalarField & alphat, const label patchi) const pure virtual
kappaEff() [2/4]
virtual tmp< scalarField > Foam::basic2TThermo::kappaEff (const scalarField & alphat, const label patchi) const pure virtual
kappaEff() [3/4]
virtual tmp< volScalarField > Foam::basic2TThermo::kappaEff (const volScalarField &) const pure virtual
kappaEff() [4/4]
virtual tmp< volScalarField > Foam::basic2TThermo::kappaEff (const volScalarField &) const pure virtual
kappaTR() [1/4]
virtual tmp< volScalarField > Foam::basic2TThermo::kappaTR () const pure virtual
kappaTR() [2/4]
virtual tmp< volScalarField > Foam::basic2TThermo::kappaTR () const pure virtual
kappaTR() [3/4]
virtual tmp< scalarField > Foam::basic2TThermo::kappaTR (const label patchi) const pure virtual
kappaTR() [4/4]
virtual tmp< scalarField > Foam::basic2TThermo::kappaTR (const label patchi) const pure virtual
kappaVib() [1/4]
virtual tmp< volScalarField > Foam::basic2TThermo::kappaVib () const pure virtual
kappaVib() [2/4]
virtual tmp< volScalarField > Foam::basic2TThermo::kappaVib () const pure virtual
kappaVib() [3/4]
virtual tmp< scalarField > Foam::basic2TThermo::kappaVib (const label patchi) const pure virtual
kappaVib() [4/4]
virtual tmp< scalarField > Foam::basic2TThermo::kappaVib (const label patchi) const pure virtual
lookupThermo() [1/2]
const Foam::basic2TThermo & Foam::basic2TThermo::lookupThermo (const fvPatchScalarField & pf) static
Definition at line 473 of file basic2TThermo/basic2TThermo.C.
lookupThermo() [2/2]
static const basic2TThermo & Foam::basic2TThermo::lookupThermo (const fvPatchScalarField & pf) static
New() [1/11]
template<class Thermo > static autoPtr< Thermo > Foam::basic2TThermo::New (const fvMesh & , const dictionary & , const word & phaseName = word::null) static
New() [2/11]
template<class Thermo > static autoPtr< Thermo > Foam::basic2TThermo::New (const fvMesh & , const dictionary & , const word & phaseName = word::null) static
New() [3/11]
template<class Thermo > static autoPtr< Thermo > Foam::basic2TThermo::New (const fvMesh & , const word & phaseName, const word & dictName) static
New() [4/11]
template<class Thermo > static autoPtr< Thermo > Foam::basic2TThermo::New (const fvMesh & , const word & phaseName, const word & dictName) static
New() [5/11]
template<class Thermo > static autoPtr< Thermo > Foam::basic2TThermo::New (const fvMesh & , const word & phaseName = word::null) static
Referenced by Foam::ne2TThermo::New(), Foam::fluid2TThermo::New(), Foam::fluid2TThermo::New(), Foam::ne2TThermo::New(), phasePropertyName(), phasePropertyName(), and phaseScopedName().
New() [6/11]
Foam::autoPtr< Foam::basic2TThermo > Foam::basic2TThermo::New (const fvMesh & mesh, const word & phaseName = word::null) static
Definition at line 440 of file basic2TThermo/basic2TThermo.C.
New() [7/11]
template<class Thermo > static autoPtr< Thermo > Foam::basic2TThermo::New (const fvMesh & , const word & phaseName = word::null) static
New() [8/11]
static autoPtr< basic2TThermo > Foam::basic2TThermo::New (const fvMesh & , const word & phaseName = word::null) static
New() [9/11]
template<class TThermo > Foam::autoPtr< TThermo > Foam::basic2TThermo::New (const fvMesh & mesh, const dictionary & dict, const word & phaseName)
Definition at line 161 of file basic2TThermo/basic2TThermoTemplates.C.
New() [10/11]
template<class TThermo > Foam::autoPtr< TThermo > Foam::basic2TThermo::New (const fvMesh & mesh, const word & phaseName)
Definition at line 131 of file basic2TThermo/basic2TThermoTemplates.C.
New() [11/11]
template<class TThermo > Foam::autoPtr< TThermo > Foam::basic2TThermo::New (const fvMesh & mesh, const word & phaseName, const word & dictName)
Definition at line 179 of file basic2TThermo/basic2TThermoTemplates.C.
p() [1/4]
Foam::volScalarField & Foam::basic2TThermo::p () virtual
Definition at line 627 of file basic2TThermo/basic2TThermo.C.
p() [2/4]
virtual volScalarField & Foam::basic2TThermo::p () virtual
p() [3/4]
const Foam::volScalarField & Foam::basic2TThermo::p () const virtual
Definition at line 633 of file basic2TThermo/basic2TThermo.C.
p() [4/4]
virtual const volScalarField & Foam::basic2TThermo::p () const virtual
phasePropertyName() [1/4]
word Foam::basic2TThermo::phasePropertyName (const word & name) const inline
Definition at line 275 of file basic2TThermo/basic2TThermo.H.
References New(), and phaseName_.
phasePropertyName() [2/4]
word Foam::basic2TThermo::phasePropertyName (const word & name) const inline
Definition at line 275 of file lnInclude/basic2TThermo.H.
References New(), and phaseName_.
phasePropertyName() [3/4]
static word Foam::basic2TThermo::phasePropertyName (const word & name, const word & phaseName) inline static
Definition at line 268 of file basic2TThermo/basic2TThermo.H.
References New().
phasePropertyName() [4/4]
static word Foam::basic2TThermo::phasePropertyName (const word & name, const word & phaseName) inline static
Definition at line 268 of file lnInclude/basic2TThermo.H.
References New().
phaseScopedName() [1/2]
word Foam::basic2TThermo::phaseScopedName (const std::string & scope, const word & name) const inline
Definition at line 282 of file basic2TThermo/basic2TThermo.H.
References New(), and phaseName_.
phaseScopedName() [2/2]
word Foam::basic2TThermo::phaseScopedName (const std::string & scope, const word & name) const inline
Definition at line 282 of file lnInclude/basic2TThermo.H.
References New(), and phaseName_.
printThermoNames() [1/2]
Foam::Ostream & Foam::basic2TThermo::printThermoNames (Ostream & os, const wordList & cmptNames, const wordList & thermoNames) static
Definition at line 74 of file basic2TThermo/basic2TThermo.C.
References splitThermoName(), and thermoName().
printThermoNames() [2/2]
static Ostream & Foam::basic2TThermo::printThermoNames (Ostream & os, const wordList & cmptNames, const wordList & thermoNames) static
read() [1/2]
bool Foam::basic2TThermo::read () virtual
Definition at line 674 of file basic2TThermo/basic2TThermo.C.
read() [2/2]
virtual bool Foam::basic2TThermo::read () virtual
rho() [1/4]
virtual tmp< volScalarField > Foam::basic2TThermo::rho () const pure virtual
Implemented in Foam::ne2TThermo, and Foam::ne2TThermo.
rho() [2/4]
virtual tmp< volScalarField > Foam::basic2TThermo::rho () const pure virtual
Implemented in Foam::ne2TThermo, and Foam::ne2TThermo.
rho() [3/4]
virtual tmp< scalarField > Foam::basic2TThermo::rho (const label patchi) const pure virtual
Implemented in Foam::ne2TThermo, and Foam::ne2TThermo.
rho() [4/4]
virtual tmp< scalarField > Foam::basic2TThermo::rho (const label patchi) const pure virtual
Implemented in Foam::ne2TThermo, and Foam::ne2TThermo.
rhoEoS() [1/2]
virtual tmp< scalarField > Foam::basic2TThermo::rhoEoS (const scalarField & p, const scalarField & TTR, const labelList & cells) const pure virtual
rhoEoS() [2/2]
virtual tmp< scalarField > Foam::basic2TThermo::rhoEoS (const scalarField & p, const scalarField & TTR, const labelList & cells) const pure virtual
splitThermoName() [1/2]
Foam::wordList Foam::basic2TThermo::splitThermoName (const std::string & thermoName, const int nExpectedCmpts) static
Definition at line 596 of file basic2TThermo/basic2TThermo.C.
Referenced by printThermoNames().
splitThermoName() [2/2]
static wordList Foam::basic2TThermo::splitThermoName (const std::string & thermoName, const int nExpectedCmpts) static
TEH_Vib() [1/4]
virtual tmp< scalarField > Foam::basic2TThermo::TEH_Vib (const scalarField & esVib, const scalarField & p, const scalarField & TTR0, const scalarField & TVib0, const label patchi) const pure virtual
TEH_Vib() [2/4]
virtual tmp< scalarField > Foam::basic2TThermo::TEH_Vib (const scalarField & esVib, const scalarField & p, const scalarField & TTR0, const scalarField & TVib0, const label patchi) const pure virtual
TEH_Vib() [3/4]
virtual tmp< scalarField > Foam::basic2TThermo::TEH_Vib (const scalarField & esVib, const scalarField & p, const scalarField & TTR0, const scalarField & TVib0, const labelList & cells) const pure virtual
TEH_Vib() [4/4]
virtual tmp< scalarField > Foam::basic2TThermo::TEH_Vib (const scalarField & esVib, const scalarField & p, const scalarField & TTR0, const scalarField & TVib0, const labelList & cells) const pure virtual
THE_TR() [1/4]
virtual tmp< scalarField > Foam::basic2TThermo::THE_TR (const scalarField & h, const scalarField & p, const scalarField & TTR0, const label patchi) const pure virtual
THE_TR() [2/4]
virtual tmp< scalarField > Foam::basic2TThermo::THE_TR (const scalarField & h, const scalarField & p, const scalarField & TTR0, const label patchi) const pure virtual
THE_TR() [3/4]
virtual tmp< scalarField > Foam::basic2TThermo::THE_TR (const scalarField & h, const scalarField & p, const scalarField & TTR0, const labelList & cells) const pure virtual
THE_TR() [4/4]
virtual tmp< scalarField > Foam::basic2TThermo::THE_TR (const scalarField & h, const scalarField & p, const scalarField & TTR0, const labelList & cells) const pure virtual
thermoName() [1/2]
virtual word Foam::basic2TThermo::thermoName () const pure virtual
Referenced by printThermoNames().
thermoName() [2/2]
virtual word Foam::basic2TThermo::thermoName () const pure virtual
TTR() [1/4]
Foam::volScalarField & Foam::basic2TThermo::TTR () virtual
Definition at line 645 of file basic2TThermo/basic2TThermo.C.
TTR() [2/4]
virtual volScalarField & Foam::basic2TThermo::TTR () virtual
TTR() [3/4]
const Foam::volScalarField & Foam::basic2TThermo::TTR () const virtual
Definition at line 639 of file basic2TThermo/basic2TThermo.C.
TTR() [4/4]
virtual const volScalarField & Foam::basic2TThermo::TTR () const virtual
TVib() [1/4]
Foam::volScalarField & Foam::basic2TThermo::TVib () virtual
Definition at line 656 of file basic2TThermo/basic2TThermo.C.
TVib() [2/4]
virtual volScalarField & Foam::basic2TThermo::TVib () virtual
TVib() [3/4]
const Foam::volScalarField & Foam::basic2TThermo::TVib () const virtual
Definition at line 650 of file basic2TThermo/basic2TThermo.C.
TVib() [4/4]
virtual const volScalarField & Foam::basic2TThermo::TVib () const virtual
updateTTR() [1/2]
bool Foam::basic2TThermo::updateTTR () const inline noexcept
Definition at line 370 of file basic2TThermo/basic2TThermo.H.
References TOwnerTR_.
updateTTR() [2/2]
bool Foam::basic2TThermo::updateTTR () const inline noexcept
Definition at line 370 of file lnInclude/basic2TThermo.H.
References TOwnerTR_.
updateTVib() [1/2]
bool Foam::basic2TThermo::updateTVib () const inline noexcept
Definition at line 376 of file basic2TThermo/basic2TThermo.H.
References TOwnerVib_.
updateTVib() [2/2]
bool Foam::basic2TThermo::updateTVib () const inline noexcept
Definition at line 376 of file lnInclude/basic2TThermo.H.
References TOwnerVib_.
validate() [1/8]
void Foam::basic2TThermo::validate (const string & app, const word & a) const
Definition at line 502 of file basic2TThermo/basic2TThermo.C.
validate() [2/8]
void Foam::basic2TThermo::validate (const string & app, const word &) const
validate() [3/8]
void Foam::basic2TThermo::validate (const string & app, const word & a, const word & b) const
Definition at line 517 of file basic2TThermo/basic2TThermo.C.
validate() [4/8]
void Foam::basic2TThermo::validate (const string & app, const word & , const word &) const
validate() [5/8]
void Foam::basic2TThermo::validate (const string & app, const word & a, const word & b, const word & c) const
Definition at line 540 of file basic2TThermo/basic2TThermo.C.
validate() [6/8]
void Foam::basic2TThermo::validate (const string & app, const word & , const word & , const word &) const
validate() [7/8]
void Foam::basic2TThermo::validate (const string & app, const word & a, const word & b, const word & c, const word & d) const
Definition at line 566 of file basic2TThermo/basic2TThermo.C.
validate() [8/8]
void Foam::basic2TThermo::validate (const string & app, const word & , const word & , const word & , const word &) const
W() [1/2]
virtual tmp< volScalarField > Foam::basic2TThermo::W () const pure virtual
W() [2/2]
virtual tmp< volScalarField > Foam::basic2TThermo::W () const pure virtual
Member Data Documentation
alpha_
volScalarField Foam::basic2TThermo::alpha_ protected
Definition at line 149 of file basic2TThermo/basic2TThermo.H.
Referenced by basic2TThermo().
dictName
static const word Foam::basic2TThermo::dictName static
Definition at line 264 of file basic2TThermo/basic2TThermo.H.
dpdt_
bool Foam::basic2TThermo::dpdt_ protected
Definition at line 134 of file basic2TThermo/basic2TThermo.H.
Referenced by dpdt().
p_
volScalarField & Foam::basic2TThermo::p_ protected
Definition at line 140 of file basic2TThermo/basic2TThermo.H.
phaseName_
const word & Foam::basic2TThermo::phaseName_ protected
Definition at line 122 of file basic2TThermo/basic2TThermo.H.
Referenced by phasePropertyName(), and phaseScopedName().
pOwner_
bool Foam::basic2TThermo::pOwner_ protected
Definition at line 125 of file basic2TThermo/basic2TThermo.H.
TOwnerTR_
bool Foam::basic2TThermo::TOwnerTR_ protected
Definition at line 128 of file basic2TThermo/basic2TThermo.H.
Referenced by basic2TThermo(), basic2TThermo(), basic2TThermo(), and updateTTR().
TOwnerVib_
bool Foam::basic2TThermo::TOwnerVib_ protected
Definition at line 131 of file basic2TThermo/basic2TThermo.H.
Referenced by basic2TThermo(), basic2TThermo(), and updateTVib().
TTR_
volScalarField & Foam::basic2TThermo::TTR_ protected
Definition at line 143 of file basic2TThermo/basic2TThermo.H.
Referenced by basic2TThermo().
TVib_
volScalarField & Foam::basic2TThermo::TVib_ protected
Definition at line 146 of file basic2TThermo/basic2TThermo.H.
The documentation for this class was generated from the following files:
basic2TThermo/basic2TThermo.H
lnInclude/basic2TThermo.H
basic2TThermo/basic2TThermo.C
basic2TThermo/basic2TThermoTemplates.C
lnInclude/basic2TThermo.C
lnInclude/basic2TThermoTemplates.C