neTCLib: Foam::blottnerEucken2TTransport< Thermo2T > Class Template Reference
Foam::blottnerEucken2TTransport< Thermo2T > Class Template Reference
#include <blottnerEucken2TTransport.H>
Public Member Functions
blottnerEucken2TTransport (const Thermo2T &t, const scalar AB, const scalar BB, const scalar CB)
blottnerEucken2TTransport (const word &, const blottnerEucken2TTransport &)
blottnerEucken2TTransport (const dictionary &dict)
blottnerEucken2TTransport (const Thermo2T &t, const dictionary &dict)
autoPtr< blottnerEucken2TTransport > clone () const
scalar mu (const scalar TTR) const
scalar kappaTR (const scalar p, const scalar TTR) const
scalar kappaVib (const scalar TTR) const
scalar alphah (const scalar p, const scalar TTR) const
void write (Ostream &os) const
void operator+= (const blottnerEucken2TTransport &)
void operator*= (const scalar)
blottnerEucken2TTransport (const Thermo2T &t, const scalar AB, const scalar BB, const scalar CB)
blottnerEucken2TTransport (const word &, const blottnerEucken2TTransport &)
blottnerEucken2TTransport (const dictionary &dict)
blottnerEucken2TTransport (const Thermo2T &t, const dictionary &dict)
autoPtr< blottnerEucken2TTransport > clone () const
scalar mu (const scalar TTR) const
scalar kappaTR (const scalar p, const scalar TTR) const
scalar kappaVib (const scalar TTR) const
scalar alphah (const scalar p, const scalar TTR) const
void write (Ostream &os) const
void operator+= (const blottnerEucken2TTransport &)
void operator*= (const scalar)
Static Public Member Functions
static autoPtr< blottnerEucken2TTransport > New (const dictionary &dict)
static word typeName ()
static autoPtr< blottnerEucken2TTransport > New (const dictionary &dict)
static word typeName ()
Friends
blottnerEucken2TTransport operator+ (const blottnerEucken2TTransport &, const blottnerEucken2TTransport &)
blottnerEucken2TTransport operator* (const scalar, const blottnerEucken2TTransport &)
Ostream & operator<< (Ostream &, const blottnerEucken2TTransport &)
blottnerEucken2TTransport operator+ (const blottnerEucken2TTransport &, const blottnerEucken2TTransport &)
blottnerEucken2TTransport operator* (const scalar, const blottnerEucken2TTransport &)
Ostream & operator<< (Ostream &, const blottnerEucken2TTransport &)
Detailed Description
template<class Thermo2T>
class Foam::blottnerEucken2TTransport< Thermo2T >
Definition at line 99 of file transport/blottnerEucken2T/blottnerEucken2TTransport.H.
Constructor & Destructor Documentation
blottnerEucken2TTransport() [1/8]
template<class Thermo2T > Foam::blottnerEucken2TTransport< Thermo2T >::blottnerEucken2TTransport (const Thermo2T & t, const scalar AB, const scalar BB, const scalar CB) inline
Definition at line 36 of file lnInclude/blottnerEucken2TTransportI.H.
blottnerEucken2TTransport() [2/8]
template<class Thermo2T > Foam::blottnerEucken2TTransport< Thermo2T >::blottnerEucken2TTransport (const word & name, const blottnerEucken2TTransport< Thermo2T > & st) inline
Definition at line 52 of file lnInclude/blottnerEucken2TTransportI.H.
blottnerEucken2TTransport() [3/8]
template<class Thermo2T > Foam::blottnerEucken2TTransport< Thermo2T >::blottnerEucken2TTransport (const dictionary & dict) explicit
Definition at line 47 of file lnInclude/blottnerEucken2TTransport.C.
blottnerEucken2TTransport() [4/8]
template<class Thermo2T > Foam::blottnerEucken2TTransport< Thermo2T >::blottnerEucken2TTransport (const Thermo2T & t, const dictionary & dict)
Definition at line 57 of file lnInclude/blottnerEucken2TTransport.C.
blottnerEucken2TTransport() [5/8]
template<class Thermo2T > Foam::blottnerEucken2TTransport< Thermo2T >::blottnerEucken2TTransport (const Thermo2T & t, const scalar AB, const scalar BB, const scalar CB) inline
blottnerEucken2TTransport() [6/8]
template<class Thermo2T > Foam::blottnerEucken2TTransport< Thermo2T >::blottnerEucken2TTransport (const word & , const blottnerEucken2TTransport< Thermo2T > &) inline
blottnerEucken2TTransport() [7/8]
template<class Thermo2T > Foam::blottnerEucken2TTransport< Thermo2T >::blottnerEucken2TTransport (const dictionary & dict) explicit
blottnerEucken2TTransport() [8/8]
template<class Thermo2T > Foam::blottnerEucken2TTransport< Thermo2T >::blottnerEucken2TTransport (const Thermo2T & t, const dictionary & dict)
Member Function Documentation
alphah() [1/2]
template<class Thermo2T > Foam::scalar Foam::blottnerEucken2TTransport< Thermo2T >::alphah (const scalar p, const scalar TTR) const inline
Definition at line 122 of file lnInclude/blottnerEucken2TTransportI.H.
References CpTR().
alphah() [2/2]
template<class Thermo2T > scalar Foam::blottnerEucken2TTransport< Thermo2T >::alphah (const scalar p, const scalar TTR) const inline
clone() [1/2]
template<class Thermo2T > Foam::autoPtr< Foam::blottnerEucken2TTransport< Thermo2T > > Foam::blottnerEucken2TTransport< Thermo2T >::clone () const inline
Definition at line 67 of file lnInclude/blottnerEucken2TTransportI.H.
Referenced by Foam::operator<<().
clone() [2/2]
template<class Thermo2T > autoPtr< blottnerEucken2TTransport > Foam::blottnerEucken2TTransport< Thermo2T >::clone () const inline
kappaTR() [1/2]
template<class Thermo2T > Foam::scalar Foam::blottnerEucken2TTransport< Thermo2T >::kappaTR (const scalar p, const scalar TTR) const inline
Definition at line 98 of file lnInclude/blottnerEucken2TTransportI.H.
References CvT().
kappaTR() [2/2]
template<class Thermo2T > scalar Foam::blottnerEucken2TTransport< Thermo2T >::kappaTR (const scalar p, const scalar TTR) const inline
kappaVib() [1/2]
template<class Thermo2T > Foam::scalar Foam::blottnerEucken2TTransport< Thermo2T >::kappaVib (const scalar TTR) const inline
Definition at line 111 of file lnInclude/blottnerEucken2TTransportI.H.
kappaVib() [2/2]
template<class Thermo2T > scalar Foam::blottnerEucken2TTransport< Thermo2T >::kappaVib (const scalar TTR) const inline
mu() [1/2]
template<class Thermo2T > Foam::scalar Foam::blottnerEucken2TTransport< Thermo2T >::mu (const scalar TTR) const inline
Definition at line 87 of file lnInclude/blottnerEucken2TTransportI.H.
mu() [2/2]
template<class Thermo2T > scalar Foam::blottnerEucken2TTransport< Thermo2T >::mu (const scalar TTR) const inline
New() [1/2]
template<class Thermo2T > Foam::autoPtr< Foam::blottnerEucken2TTransport< Thermo2T > > Foam::blottnerEucken2TTransport< Thermo2T >::New (const dictionary & dict) inline static
Definition at line 75 of file lnInclude/blottnerEucken2TTransportI.H.
Referenced by Foam::operator<<().
New() [2/2]
template<class Thermo2T > static autoPtr< blottnerEucken2TTransport > Foam::blottnerEucken2TTransport< Thermo2T >::New (const dictionary & dict) inline static
operator*=() [1/2]
template<class Thermo2T > void Foam::blottnerEucken2TTransport< Thermo2T >::operator*= (const scalar s) inline
Definition at line 158 of file lnInclude/blottnerEucken2TTransportI.H.
operator*=() [2/2]
template<class Thermo2T > void Foam::blottnerEucken2TTransport< Thermo2T >::operator*= (const scalar) inline
operator+=() [1/2]
template<class Thermo2T > void Foam::blottnerEucken2TTransport< Thermo2T >::operator+= (const blottnerEucken2TTransport< Thermo2T > & st) inline
Definition at line 136 of file lnInclude/blottnerEucken2TTransportI.H.
operator+=() [2/2]
template<class Thermo2T > void Foam::blottnerEucken2TTransport< Thermo2T >::operator+= (const blottnerEucken2TTransport< Thermo2T > &) inline
typeName() [1/2]
template<class Thermo2T > static word Foam::blottnerEucken2TTransport< Thermo2T >::typeName () inline static
Definition at line 150 of file lnInclude/blottnerEucken2TTransport.H.
typeName() [2/2]
template<class Thermo2T > static word Foam::blottnerEucken2TTransport< Thermo2T >::typeName () inline static
Definition at line 150 of file transport/blottnerEucken2T/blottnerEucken2TTransport.H.
write() [1/2]
template<class Thermo2T > void Foam::blottnerEucken2TTransport< Thermo2T >::write (Ostream & os) const
Definition at line 73 of file lnInclude/blottnerEucken2TTransport.C.
write() [2/2]
template<class Thermo2T > void Foam::blottnerEucken2TTransport< Thermo2T >::write (Ostream & os) const
Friends And Related Symbol Documentation
operator* [1/2]
template<class Thermo2T > blottnerEucken2TTransport operator* (const scalar , const blottnerEucken2TTransport< Thermo2T > &) friend
operator* [2/2]
template<class Thermo2T > blottnerEucken2TTransport operator* (const scalar , const blottnerEucken2TTransport< Thermo2T > &) friend
operator+ [1/2]
template<class Thermo2T > blottnerEucken2TTransport operator+ (const blottnerEucken2TTransport< Thermo2T > & , const blottnerEucken2TTransport< Thermo2T > &) friend
operator+ [2/2]
template<class Thermo2T > blottnerEucken2TTransport operator+ (const blottnerEucken2TTransport< Thermo2T > & , const blottnerEucken2TTransport< Thermo2T > &) friend
operator<< [1/2]
template<class Thermo2T > Ostream & operator<< (Ostream & , const blottnerEucken2TTransport< Thermo2T > &) friend
operator<< [2/2]
template<class Thermo2T > Ostream & operator<< (Ostream & , const blottnerEucken2TTransport< Thermo2T > &) friend
The documentation for this class was generated from the following files:
lnInclude/blottnerEucken2TTransport.H
transport/blottnerEucken2T/blottnerEucken2TTransport.H
lnInclude/blottnerEucken2TTransport.C
lnInclude/blottnerEucken2TTransportI.H
transport/blottnerEucken2T/blottnerEucken2TTransport.C
transport/blottnerEucken2T/blottnerEucken2TTransportI.H