neTCLib: EtoHthermo2T.H File Reference
EtoHthermo2T.H File Reference
Functions
scalar CpTR (const scalar p, const scalar TTR) const
scalar HsTR (const scalar p, const scalar TTR) const
scalar HaTR (const scalar p, const scalar TTR) const
Function Documentation
CpTR()
scalar CpTR (const scalar p, const scalar TTR) const inline
Definition at line 1 of file lnInclude/EtoHthermo2T.H.
References CvT().
Referenced by Foam::blottnerEucken2TTransport< Thermo2T >::alphah(), Foam::he2TThermo< BasicNe2TThermo, MixtureType >::alphaheTR(), Foam::species::thermo2T< Thermo2T, Type >::cpTR(), CvT(), Foam::species::thermo2T< Thermo2T, Type >::gamma(), Foam::he2TThermo< Basic2TThermo, MixtureType >::kappaEff(), Foam::he2TThermo< Basic2TThermo, MixtureType >::kappaEff(), Foam::he2TThermo< BasicNe2TThermo, MixtureType >::kappaEff(), Foam::he2TThermo< Basic2TThermo, MixtureType >::kappaTR(), Foam::he2TThermo< Basic2TThermo, MixtureType >::kappaTR(), Foam::he2TThermo< Basic2TThermo, MixtureType >::kappaVib(), and Foam::he2TThermo< Basic2TThermo, MixtureType >::kappaVib().
HaTR()
scalar HaTR (const scalar p, const scalar TTR) const inline
Definition at line 31 of file lnInclude/EtoHthermo2T.H.
HsTR()
scalar HsTR (const scalar p, const scalar TTR) const inline
Definition at line 16 of file lnInclude/EtoHthermo2T.H.